/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_MainActivity */

#ifndef _Included_com_example_hellojni_MainActivity
#define _Included_com_example_hellojni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_hellojni_MainActivity_nativDicInit
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_com_example_hellojni_MainActivity_nativTrackInit
        (JNIEnv *, jobject, jlongArray);

JNIEXPORT void JNICALL Java_com_example_hellojni_MainActivity_nativTrackIter
        (JNIEnv *, jobject, jbyteArray);

JNIEXPORT jlong JNICALL Java_com_example_hellojni_MainActivity_nativGetWord
        (JNIEnv *, jobject);

JNIEXPORT jbyte JNICALL Java_com_example_hellojni_MainActivity_nativGetCharValue
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_example_hellojni_MainActivity_nativGetCharIndex
        (JNIEnv *, jobject);

JNIEXPORT jboolean JNICALL Java_com_example_hellojni_MainActivity_nativFindWord
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
